apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-deployment
  labels:
    app: trend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend
  template:
    metadata:
      labels:
        app: trend
    spec:
      containers:
        - name: trend
          image: madhan14/trend:v1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 6
            periodSeconds: 15
